# Generated by Django 6.0.1 on 2026-03-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='班级'),
        ),
    ]
