# Generated by Django 6.0.1 on 2026-03-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_classname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
