# Generated by Django 5.1.6 on 2025-03-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='raw_password',
            field=models.CharField(max_length=20, null=True, verbose_name='明文密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super', '超级管理员'), ('admin', '管理员'), ('normal', '普通')], default='normal', max_length=20, verbose_name='权限'),
        ),
    ]
