# Generated by Django 5.1.6 on 2025-03-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_raw_password_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='raw_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='明文密码'),
        ),
    ]
