# Generated by Django 5.1.6 on 2025-03-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',), 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
