# Generated by Django 5.1.6 on 2025-03-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='css',
            field=models.TextField(blank=True, null=True, verbose_name='CSS代码'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='html',
            field=models.TextField(blank=True, null=True, verbose_name='HTML代码'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='js',
            field=models.TextField(blank=True, null=True, verbose_name='JS代码'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0, verbose_name='分数'),
        ),
    ]
