# Generated by Django 6.0.1 on 2026-03-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
        ('submission', '0002_remove_submission_referee_alter_submission_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='prompt.conversation', verbose_name='对话'),
        ),
    ]
