# Generated by Django 5.1.6 on 2025-03-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_alter_submission_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-created',)},
        ),
    ]
