# Generated by Django 6.0.1 on 2026-03-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_submission_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='flag',
            field=models.CharField(blank=True, choices=[('red', '值得展示'), ('blue', '需要讲解'), ('green', '优秀作品'), ('yellow', '需要改进')], db_index=True, default=None, max_length=10, null=True, verbose_name='标记'),
        ),
    ]
