# Generated by Django 6.0.1 on 2026-03-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_add_flag_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='nominated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='参与排名'),
        ),
        migrations.AddField(
            model_name='submission',
            name='raw_score',
            field=models.FloatField(default=0.0, verbose_name='原始加权分'),
        ),
    ]
