# Generated by Django 5.1.6 on 2025-03-18 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
