# Generated by Django 6.0.1 on 2026-03-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_remove_nominated'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='zone',
            field=models.CharField(blank=True, choices=[('featured', '精选'), ('low', '待改进'), ('pending', '待评')], db_index=True, default=None, max_length=10, null=True, verbose_name='分区'),
        ),
    ]
