# Generated by Django 6.0.1 on 2026-03-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_add_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='查看次数'),
        ),
    ]
