# Generated by Django 6.0.1 on 2026-03-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_add_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='conversation',
        ),
    ]
