# Generated by Django 6.0.1 on 2026-03-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='prompt_level',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='提示词层级'),
        ),
    ]
