# Generated by Django 6.0.1 on 2026-03-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0002_message_prompt_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.CharField(default='ai', max_length=10),
        ),
    ]
