# Generated by Django 6.0.1 on 2026-03-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0003_add_message_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='source',
            field=models.CharField(default='conversation', max_length=12),
        ),
    ]
