# Generated by Django 6.0.1 on 2026-04-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0004_update_message_source_default'),
        ('submission', '0010_remove_conversation_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_message', to='submission.submission'),
        ),
    ]
