# Generated by Django 6.0.1 on 2026-04-16 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0005_message_add_submission_fk'),
        ('submission', '0010_remove_conversation_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_message', to='submission.submission'),
        ),
    ]
