# Generated by Django 5.1.6 on 2025-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='display',
            field=models.IntegerField(unique=True),
        ),
    ]
