# Generated by Django 5.1.6 on 2025-03-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_alter_tutorial_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name': '教程', 'verbose_name_plural': '教程'},
        ),
    ]
