# Generated by Django 5.1.6 on 2025-03-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_alter_tutorial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ('display',), 'verbose_name': '教程', 'verbose_name_plural': '教程'},
        ),
    ]
