# Generated by Django 5.1.6 on 2025-03-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='display',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
