# Generated by Django 6.0.1 on 2026-03-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterField(
            model_name='task',
            name='display',
            field=models.IntegerField(db_index=True, verbose_name='序号'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('display', 'task_type')},
        ),
    ]
