# Generated by Django 6.0.1 on 2026-03-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_options_alter_task_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='pass_score',
            field=models.FloatField(blank=True, null=True, verbose_name='通过分数线'),
        ),
    ]
