# Generated by Django 6.0.1 on 2026-04-13 09:33

import django.db.models.deletion
import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_challenge_pass_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名')),
                ('file', models.FileField(upload_to=task.models.task_asset_upload_to, verbose_name='文件')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='task.task')),
            ],
            options={
                'verbose_name': '任务素材',
                'verbose_name_plural': '任务素材',
                'unique_together': {('task', 'name')},
            },
        ),
    ]
