# Generated by Django 6.0.1 on 2026-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_challenge_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='example_css',
            field=models.TextField(blank=True, null=True, verbose_name='示例CSS'),
        ),
        migrations.AddField(
            model_name='task',
            name='example_html',
            field=models.TextField(blank=True, null=True, verbose_name='示例HTML'),
        ),
        migrations.AddField(
            model_name='task',
            name='example_js',
            field=models.TextField(blank=True, null=True, verbose_name='示例JS'),
        ),
    ]
